'use client';
import { useEffect, useRef, useState } from 'react';
import { Eye, EyeOff, LockKeyhole, UnlockKeyhole, Plus, Trash2, FolderPlus, SquareDashed, SlidersHorizontal, History, Type, Image as ImageIcon, ChevronDown, ChevronRight, MoreHorizontal, Copy, ArrowUp, ArrowDown, AlignLeft, AlignCenter, AlignRight, RotateCcw, Sparkles, Sun, Contrast, Droplets, Palette, Focus, Triangle, Layers, Check, PenTool } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator } from '@/components/ui/dropdown-menu';
import { StudioEngine } from '@/lib/studio/engine';
import { defaultFilters, makeLayer, type Layer, type Filters } from '@/lib/studio/types';
import { context, createCanvas } from '@/lib/studio/pixels';
import { IconButton, Range, Choice, NumberBox } from './controls';
import { toast } from 'sonner';
export function LayerThumb({ layer, engine, revision }: {
    layer: Layer;
    engine: StudioEngine;
    revision: number;
}) { const ref = useRef<HTMLCanvasElement>(null); useEffect(() => { if (!ref.current)
    return; const c = ref.current, ctx = context(c); ctx.clearRect(0, 0, c.width, c.height); if (layer.kind === 'raster' || layer.kind === 'shape') {
    const bitmap = engine.layerBitmap(layer);
    const scale = Math.min(40 / bitmap.width, 30 / bitmap.height);
    ctx.drawImage(bitmap, (40 - bitmap.width * scale) / 2, (30 - bitmap.height * scale) / 2, bitmap.width * scale, bitmap.height * scale);
} }, [layer, revision]); return <span className={'layer-thumb ' + layer.kind}>{layer.kind === 'text' ? <Type size={18}/> : layer.kind === 'adjustment' ? <SlidersHorizontal size={16}/> : layer.kind === 'group' ? <FolderPlus size={18}/> : <canvas ref={ref} width="40" height="30"/>}</span>; }
const blends = [['source-over', 'Normal'], ['multiply', 'Multiply'], ['screen', 'Screen'], ['overlay', 'Overlay'], ['darken', 'Darken'], ['lighten', 'Lighten'], ['soft-light', 'Soft light'], ['hard-light', 'Hard light'], ['difference', 'Difference']] as [
    string,
    string
][];
export default function Dock({ engine: e, revision, tab, setTab, onText, onMagic, primary, setPrimary, onAction }: {
    engine: StudioEngine;
    revision: number;
    tab: string;
    setTab: (s: string) => void;
    onText: () => void;
    onMagic: () => void;
    primary: string;
    setPrimary: (s: string) => void;
    onAction: (a: () => void) => void;
}) {
    const l = e.active;
    const [filterGroup, setFilterGroup] = useState('light'), [dragged, setDragged] = useState(''), [bottomTab, setBottomTab] = useState('layers');
    const update = (patch: Partial<Layer>, label?: string) => { if (l) {
        if (l.locked && !('locked' in patch) && !('visible' in patch)) {
            toast.info('Unlock the layer to edit its properties.');
            return;
        }
        e.update(l.id, patch, label);
    } };
    const adjust = (key: keyof Filters, value: number) => { if (!l || l.locked)
        return; update({ filters: { ...l.filters, [key]: value } }); };
    const commitAdjustment = () => e.commit('Adjust ' + (l?.name ?? 'layer'));
    const hasFilters = l && Object.values(l.filters).some(Boolean);
    function addAdjustment() { const a = makeLayer('Color adjustment', 'adjustment', e.doc.width, e.doc.height); a.filters = { ...defaultFilters }; e.add(a, 'Add adjustment layer'); setTab('adjustments'); }
    return <aside className="studio-dock">
  <Tabs value={tab} onValueChange={setTab} className="properties-tabs"><TabsList className="dock-tabs" variant="line"><TabsTrigger value="properties">Properties</TabsTrigger><TabsTrigger value="adjustments">Adjustments</TabsTrigger><TabsTrigger value="history"><History size={16}/><span className="sr-only">History</span></TabsTrigger></TabsList>
   <TabsContent value="properties" className="property-content">
    <div className="panel-title"><span>{l?.kind === 'text' ? 'Character' : 'Transform'}</span><span className="panel-meta">{l?.kind === 'text' ? 'TYPE LAYER' : l?.kind === 'raster' ? 'PIXEL LAYER' : l?.kind.toUpperCase() ?? 'DOCUMENT'}</span></div>
    {l?.kind === 'text' && l.text ? <><Choice label="Font family" value={l.text.font} onChange={font => update({ text: { ...l.text!, font } }, 'Change font')} options={['Arial', 'Georgia', 'Verdana', 'Courier New', 'Trebuchet MS', 'Times New Roman']}/><div className="property-grid"><Choice label="Font weight" value={String(l.text.weight)} onChange={v => update({ text: { ...l.text!, weight: Number(v) } }, 'Change font weight')} options={[["400", "Regular"], ["500", "Medium"], ["600", "Semibold"], ["700", "Bold"], ["900", "Black"]]}/><NumberBox label="Size" suffix="px" min={6} max={600} value={l.text.size} onChange={size => update({ text: { ...l.text!, size } }, 'Change type size')}/><NumberBox label="↔" value={l.text.tracking} min={-20} max={100} suffix="px" onChange={tracking => update({ text: { ...l.text!, tracking } }, 'Change tracking')}/><NumberBox label="↕" value={l.text.leading} min={.5} max={4} onChange={leading => update({ text: { ...l.text!, leading } }, 'Change leading')}/></div><div className="text-style-row"><div className="segmented">{[['left', AlignLeft], ['center', AlignCenter], ['right', AlignRight]].map(([a, Icon]) => <IconButton key={String(a)} label={'Align ' + a} active={l.text?.align === a} onClick={() => update({ text: { ...l.text!, align: a as 'left' | 'center' | 'right' } }, 'Align text')}><Icon size={16}/></IconButton>)}</div><label className="color-field"><input type="color" aria-label="Text color" value={l.color} onChange={ev => update({ color: ev.target.value })} onBlur={() => e.commit('Change text color')}/><span>{l.color.toUpperCase()}</span></label><IconButton label="Italic" active={l.text.italic} onClick={() => update({ text: { ...l.text!, italic: !l.text!.italic } }, 'Toggle italic')}><i>I</i></IconButton></div><button className="secondary-button full-width" onClick={onText}><Type size={14}/>Edit text</button></> : <><div className="property-grid"><NumberBox label="W" suffix="px" min={1} max={8192} value={l?.w ?? e.doc.width} onChange={w => update({ w }, 'Resize layer')}/><NumberBox label="H" suffix="px" min={1} max={8192} value={l?.h ?? e.doc.height} onChange={h => update({ h }, 'Resize layer')}/><NumberBox label="X" value={l?.x ?? 0} suffix="px" onChange={x => update({ x }, 'Position layer')}/><NumberBox label="Y" value={l?.y ?? 0} suffix="px" onChange={y => update({ y }, 'Position layer')}/></div><div className="property-grid"><NumberBox label="↻" suffix="°" value={l?.rotation ?? 0} onChange={rotation => update({ rotation }, 'Rotate layer')}/><button className="secondary-button" onClick={() => update({ x: (e.doc.width - (l?.w ?? 0)) / 2, y: (e.doc.height - (l?.h ?? 0)) / 2 }, 'Center layer')}>Center layer</button></div>{l?.kind === 'shape' && <label className="color-field wide"><input type="color" aria-label="Shape color" value={l.color} onChange={ev => update({ color: ev.target.value })} onBlur={() => e.commit('Change shape color')}/><span>Fill color</span><code>{l.color.toUpperCase()}</code></label>}</>}
    <div className="panel-divider"/><div className="panel-title"><span>Quick actions</span><Sparkles size={14}/></div><div className="quick-actions"><button onClick={onMagic}><Sparkles size={15}/>Remove background</button><button onClick={addAdjustment}><SlidersHorizontal size={15}/>Add adjustment</button></div>
   </TabsContent>
   <TabsContent value="adjustments" className="property-content adjustment-content"><div className="panel-title"><span>Live adjustments</span><IconButton label="Reset adjustments" disabled={!hasFilters} onClick={() => update({ filters: { ...defaultFilters } }, 'Reset adjustments')}><RotateCcw size={14}/></IconButton></div><div className="adjustment-categories">{[['light', Sun, 'Light'], ['color', Palette, 'Color'], ['detail', Focus, 'Detail']].map(([v, Icon, label]) => <button key={String(v)} className={filterGroup === v ? 'selected' : ''} onClick={() => setFilterGroup(v as string)}><Icon size={18}/><span>{String(label)}</span></button>)}</div><div className="filter-sliders">{(filterGroup === 'light' ? [['brightness', 'Brightness', -100, 100], ['contrast', 'Contrast', -100, 100]] : filterGroup === 'color' ? [['hue', 'Hue', -180, 180], ['saturation', 'Saturation', -100, 100], ['red', 'Cyan — Red', -100, 100], ['green', 'Magenta — Green', -100, 100], ['blue', 'Yellow — Blue', -100, 100]] : [['blur', 'Gaussian blur', 0, 30], ['sharpness', 'Sharpness', 0, 100]]).map(([key, label, min, max]) => <Range key={key} label={String(label)} value={l?.filters[key as keyof Filters] ?? 0} min={Number(min)} max={Number(max)} onChange={v => adjust(key as keyof Filters, v)} onCommit={commitAdjustment}/>)}</div><div className="adjustment-note"><span className="tiny-dot"/>Non-destructive · {l?.name ?? 'Select a layer'}</div><button className="secondary-button full-width" onClick={addAdjustment}><Plus size={14}/>New adjustment layer</button></TabsContent>
   <TabsContent value="history" className="history-content"><div className="panel-title"><span>Document history</span><span className="panel-meta">{e.history.length} steps</span></div><div className="history-list">{e.history.map((h, i) => <button key={h.id} className={'history-row ' + (i === e.historyIndex ? 'current ' : '') + (i > e.historyIndex ? 'future' : '')} onClick={() => e.goHistory(i)}>{i === e.historyIndex ? <Check size={15}/> : <History size={15}/>}<span>{h.label}</span><small>{new Date(h.time).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</small></button>)}</div></TabsContent>
  </Tabs>
  <div className="color-strip"><label><input type="color" aria-label="Foreground color" value={primary} onChange={ev => setPrimary(ev.target.value)}/><span>Color</span></label><div className="palette">{['#ffffff', '#121215', '#6366f1', '#a78bfa', '#06b6d4', '#a3e635', '#f59e0b', '#f472b6'].map(c => <button key={c} aria-label={'Use ' + c} className={primary === c ? 'selected' : ''} style={{ background: c }} onClick={() => setPrimary(c)}/>)}</div></div>
  <Tabs value={bottomTab} onValueChange={setBottomTab} className="layer-tabs"><TabsList className="dock-tabs" variant="line"><TabsTrigger value="layers">Layers <span className="count-badge">{e.doc.layers.length}</span></TabsTrigger><TabsTrigger value="channels">Channels</TabsTrigger><TabsTrigger value="paths">Paths</TabsTrigger></TabsList>
   <TabsContent value="layers" className="layers-content"><div className="layer-options"><Choice label="Blend mode" value={l?.blend ?? 'source-over'} options={blends} onChange={blend => update({ blend: blend as GlobalCompositeOperation }, 'Change blend mode')}/><label className="compact-number">Opacity <input aria-label="Layer opacity" type="number" min={0} max={100} value={l?.opacity ?? 100} onChange={ev => update({ opacity: Math.max(0, Math.min(100, Number(ev.target.value))) })} onBlur={() => e.commit('Layer opacity')}/><span>%</span></label></div><div className="layer-lock-row"><span>Lock:</span><IconButton label={l?.locked ? 'Unlock layer' : 'Lock layer'} active={l?.locked} onClick={() => update({ locked: !l?.locked }, 'Toggle lock')}><LockKeyhole size={13}/></IconButton><Range label="Fill" value={l?.fill ?? 100} onChange={fill => update({ fill })} onCommit={() => e.commit('Layer fill')} suffix="%"/></div>
    <div className="layer-list" role="list" aria-label="Document layers">{[...e.doc.layers].reverse().map(layer => <div key={layer.id} role="listitem" draggable onDragStart={() => setDragged(layer.id)} onDragOver={ev => ev.preventDefault()} onDrop={ev => { ev.preventDefault(); if (dragged)
            e.reorder(dragged, e.doc.layers.indexOf(layer)); setDragged(''); }} className={'layer-row ' + (e.selected === layer.id ? 'selected ' : '') + (!layer.visible ? 'hidden-layer ' : '') + (layer.parent ? 'child-layer' : '')} onClick={() => e.select(layer.id)} onDoubleClick={() => { e.select(layer.id); if (layer.kind === 'text')
            onText(); }}>
     <button className="layer-eye" aria-label={(layer.visible ? 'Hide ' : 'Show ') + layer.name} onClick={ev => { ev.stopPropagation(); e.update(layer.id, { visible: !layer.visible }, 'Toggle visibility'); }}>{layer.visible ? <Eye size={15}/> : <EyeOff size={15}/>}</button><button className="layer-main" aria-label={'Select ' + layer.name} onClick={() => e.select(layer.id)}><LayerThumb layer={layer} engine={e} revision={revision}/><span className="layer-name">{layer.name}<small>{layer.kind === 'text' ? 'Editable text' : layer.kind === 'adjustment' ? 'Live adjustment' : layer.kind === 'raster' ? 'Image layer' : layer.kind === 'group' ? 'Layer group' : 'Vector shape'}</small></span></button>{layer.mask && <span title="Layer mask" className="mask-thumbnail"/>}{layer.locked && <LockKeyhole size={12}/>}<DropdownMenu><DropdownMenuTrigger asChild><button className="layer-more" aria-label={'Options for ' + layer.name} onClick={() => e.select(layer.id)}><MoreHorizontal size={16}/></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={() => { const name = window.prompt('Layer name', layer.name); if (name)
            e.update(layer.id, { name }, 'Rename layer'); }}>Rename</DropdownMenuItem><DropdownMenuItem onSelect={() => e.duplicate()}>Duplicate</DropdownMenuItem><DropdownMenuItem onSelect={() => e.reorder(layer.id, e.doc.layers.indexOf(layer) + 1)}>Bring forward</DropdownMenuItem><DropdownMenuItem onSelect={() => e.reorder(layer.id, e.doc.layers.indexOf(layer) - 1)}>Send backward</DropdownMenuItem>{layer.kind === 'group' && <DropdownMenuItem onSelect={() => e.ungroup()}>Ungroup</DropdownMenuItem>}<DropdownMenuSeparator /><DropdownMenuItem onSelect={() => e.deleteLayer()} disabled={layer.locked} variant="destructive">Delete</DropdownMenuItem></DropdownMenuContent></DropdownMenu>
    </div>)}</div>
    <div className="layer-footer"><span>{e.doc.layers.filter(l => l.visible).length} visible layers</span><IconButton label="Add layer mask" onClick={() => onAction(() => e.addMask())}><SquareDashed size={16}/></IconButton><IconButton label="Group selected layer" onClick={() => e.group()}><FolderPlus size={16}/></IconButton><IconButton label="New layer" onClick={() => onAction(() => e.newLayer())}><Plus size={17}/></IconButton><IconButton label="Delete selected layer" disabled={l?.locked || !l} onClick={() => e.deleteLayer()}><Trash2 size={15}/></IconButton></div>
   </TabsContent>
   <TabsContent value="channels" className="channel-content"><button className="channel-row" onClick={() => { e.channels = [true, true, true]; e.notify(); }}><span className="channel-dot rgb"/><span>RGB</span><small>Composite</small><Eye size={15}/></button>{['Red', 'Green', 'Blue'].map((name, i) => <button key={name} className="channel-row" onClick={() => { e.channels[i] = !e.channels[i]; e.notify(); }}><span className="channel-dot" style={{ background: ['#ef6269', '#5bba86', '#638bf3'][i] }}/><span>{name}</span><small>8-bit</small>{e.channels[i] ? <Eye size={15}/> : <EyeOff size={15}/>}</button>)}<p className="panel-help">Channel toggles affect the preview. Exports retain the full RGB image.</p></TabsContent>
   <TabsContent value="paths" className="path-content">{e.doc.paths.length ? e.doc.paths.map(path => <div className="path-row" key={path.id}><PenTool size={16}/><button onClick={() => { const xs = path.points.map(p => p.x), ys = path.points.map(p => p.y); e.selection = { kind: 'polygon', points: path.points, x: Math.min(...xs), y: Math.min(...ys), w: Math.max(...xs) - Math.min(...xs), h: Math.max(...ys) - Math.min(...ys) }; e.notify(); }}>{path.name}<small>{path.points.length} anchor points · click to select</small></button><IconButton label={'Delete ' + path.name} onClick={() => { e.doc.paths = e.doc.paths.filter(p => p.id !== path.id); e.commit('Delete path'); }}><Trash2 size={14}/></IconButton></div>) : <div className="panel-empty"><PenTool size={24}/><span>No paths yet</span><p>Use the Pen tool (P) and press Enter to save a path.</p></div>}</TabsContent>
  </Tabs>
  <button className="magic-dock-button" onClick={onMagic}><span className="magic-icon"><Sparkles size={18}/></span><span>Make room for a little magic<small>Explore smart editing tools</small></span><ChevronRight size={16}/></button>
 </aside>;
}
